#        _          _          _ _
#  _ __ (_)_  _____| | ___  __| (_)
# | '_ \| \ \/ / _ \ |/ _ \/ _` | |
# | |_) | |>  <  __/ |  __/ (_| | |
# | .__/|_/_/\_\___|_|\___|\__,_|_|
# |_|
# https://links.pixeledi.eu
# CYD mit ESPHome | 05.2025
#

esphome: 
  name: cyd
  friendly_name: cyd

esp32:
  board: esp32dev
  framework: 
    type: arduino 

logger: 

output: 
  - platform: ledc
    pin: GPIO21
    id: backlight_pwm
  - platform: gpio
    pin: GPIO4
    id: gpio4_out
    inverted: true

light: 
  - platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    id: backlight
    restore_mode: ALWAYS_ON
  - platform: binary
    output: gpio4_out
    id: local_light
    name: "GPIO 4 Light"
    on_state:
      - lvgl.widget.update:
          id: light_switch
          state:
            checked: !lambda return id(local_light).current_values.is_on();

spi:
  - id: tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12
  - id: touch
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39


touchscreen:
  - platform: xpt2046
    id: my_touch
    spi_id: touch
    cs_pin: GPIO33
    interrupt_pin: GPIO36
    calibration:
      x_min: 200
      x_max: 3900
      y_min: 200
      y_max: 3900   
    transform:
      mirror_x: false
      mirror_y: false
      swap_xy: false


lvgl:
  buffer_size: 25%
  touchscreens:
    - my_touch
  pages:
    - id: main_page
      widgets:
        - switch:
            id: light_switch
            align: CENTER
            on_click:
              light.toggle: local_light

display:
  - platform: ili9xxx
    spi_id: tft
    model: ili9341
    dc_pin: GPIO2
    cs_pin: GPIO15
    rotation: 90
    invert_colors: false
    # color_palette: 8BIT
